version: '2.4'

services:

  currency-exchange:
    image: mirajulislam/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 900m
    ports:
      - "8000:8000"
    networks:
      - currency-network

networks:
  currency-network: